server:
  port: 8081
hf:
  routes:
    minio-url: ${GATEWAY_MINIO_URL}
    app-url: ${GATEWAY_APP_URL}

spring:
  config:
    import:
      - optional:classpath:.env[.properties]
logging:
  level:
    com.home.funny.gateway: debug