version: '3'
services:
  minio:
    image: quay.io/minio/minio:RELEASE.2023-05-27T05-56-19Z
    container_name: minio
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - ./data/minio:/data
    command: server /data --console-address ":9001"
  mysql:
    image: mysql:8.0.33
    container_name: mysql_8
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: dev_jian
    volumes:
      - ./data/mysql:/var/lib/mysql
  redis:
    image: redis:6.0
    container_name: redis_6
    volumes:
      - ./data/redis:/data
    command: redis-server --requirepass 123456
    ports:
      - "6379:6379"
  oracle:
    image: container-registry.oracle.com/database/free:latest
    container_name: oracle
    volumes:
      - ./data/oracle/oradata:/opt/oracle/oradata
    ports:
      - "1521:1521"
    environment:
      ORACLE_PWD: 123456
    ulimits:
      nofile: 65535
      nproc: 65535