spring:
  application:
    name: home-funny

  profiles:
    active: default
  servlet:
    multipart:
      max-file-size: 100GB
      max-request-size: 1000GB
  web:
    resources:
      static-locations:
        - "classpath:/META-INF/resources/"
        - "classpath:/resources/"
        - "classpath:/static/"
        - "classpath:/public/"
        - "file:static/"
  config:
    import:
      - optional:classpath:.env[.properties]