server:
  port: 8080
spring:
  datasource:
    username: ${DATASOURCE_USERNAME}
    password: ${DATASOURCE_PASSWORD}
    url: ${DATASOURCE_URL}
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: true
s3:
  endpoint: ${S3_ENTRYPOINT}
  access: ${S3_ACCESS}
  secret: ${S3_SECRET}
  budget: ${S3_BUDGET}
logging:
  level:
    com.home.funny: debug
    sql: debug